
spring.datasource:
  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
  driverClassName: org.h2.Driver
  username: sa
  password: password
spring.jooq:
  sql-dialect: h2
spring.h2:
  console.enabled: true
spring.sql:
  init.mode: always